quarkus:
  hibernate-orm:
    database:
      generation:
        create-schemas: true
    log:
      sql: true
  datasource:
    devservices:
      port: 5433
      reuse: false
  rest-client:
    rental-api:
      url: http://localhost:8082
  smallrye-graphql-client:
    inventory:
      url: http://localhost:8083/graphql
